name: justrightapp
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.9.0
  get: ^4.6.5
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.3
  chewie: ^1.7.0
  video_player: ^2.7.0
  flutter_slidable: ^3.0.0
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  wheel_slider: ^1.1.1
  shared_preferences: ^2.2.0
  fl_chart: ^0.63.0
  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.4
  lottie: ^2.6.0
  liquid_progress_indicator: ^0.4.0
  get_storage: ^2.1.1
  http: ^1.1.0
  intl: ^0.18.1
  adaptive_dialog: ^1.9.0
  image_picker: ^1.0.2
  firebase_storage: ^11.2.6
  # permission_handler: ^10.4.3
  # flutter_file_downloader: ^1.1.2
  # image_gallery_saver: ^2.0.3
  # just_audio: ^0.9.33
  # skeleton_loader: ^2.0.0+4
  # shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/fonts/
     - assets/videos/
     - assets/animation/
  fonts:
     - family: poppinsBold
       fonts:
         - asset: assets/fonts/Poppins-Bold.ttf
     - family: poppinsMedium
       fonts:
         - asset: assets/fonts/Poppins-Medium.ttf
     - family: poppinsRegular
       fonts:
         - asset: assets/fonts/Poppins-Regular.ttf
     - family: poppinsSemiBold
       fonts:
         - asset: assets/fonts/Poppins-SemiBold.ttf
     - family: openSansRegular
       fonts:
         - asset: assets/fonts/OpenSans-Regular.ttf
     - family: openSansSemiBold
       fonts:
         - asset: assets/fonts/OpenSans-SemiBold.ttf
     - family: Rubik-Regular
       fonts:
         - asset: assets/fonts/Rubik-Regular.ttf
     - family: OpenSans-CondenssedSemiBold
       fonts:
         - asset: assets/fonts/OpenSans-CondenssedSemiBold.ttf
     - family: Integral-Regular
       fonts:
         - asset: assets/fonts/Integral-Regular.otf
     - family: Inter-Regular
       fonts:
         - asset: assets/fonts/Inter-Regular.ttf
     - family: Poppins-ExtraLight
       fonts:
         - asset: assets/fonts/Poppins-ExtraLight.ttf
     - family: Poppins-ExtraBold
       fonts:
         - asset: assets/fonts/Poppins-ExtraBold.ttf